@startuml
left to right direction
skinparam packageStyle rectangle

actor "Клиент" as Client
actor "ОС (обмен файлами)" as OS

rectangle "Мобильное банковское приложение" as App {
  usecase "Открыть\n"Дебетовая карта"" as UC_OpenDebit
  usecase "Открыть\n"QR-код для пополнения"" as UC_OpenTopUpQR
  usecase "Просмотреть QR-код\nдля пополнения" as UC_ViewQR
  usecase "Сгенерировать PDF\nс QR-кодом" as UC_GenPdfQR
  usecase "Отправить QR-код\n(PDF)" as UC_SendQR
}

Client --> UC_OpenDebit : c раздела 'Главная'
UC_OpenDebit .> UC_OpenTopUpQR : include
UC_OpenTopUpQR .> UC_ViewQR : include

UC_ViewQR .> UC_GenPdfQR : include
UC_GenPdfQR .> UC_SendQR : extends
OS <-- UC_SendQR
@enduml
